2021/FALL/FISD/SEM/Science/Science/Pages/AdminDirectory/Admin.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Science.Infrastructure.AdminStatistic;
using Science.Models;
using Science.Pages.AccountDirectory;
using Science.Services;
using Science.Services.Database.AdminDb;
using TimeSpan = Science.Infrastructure.TimeSpan;

namespace Science.Pages.AdminDirectory
{
    public class Admin : CommonPage
    {
        private readonly IAdminRepository _adminRepository;

        public Admin(IAdminRepository adminRepository)
        {
            _adminRepository = adminRepository;
        }

        public Statistic Registrations { get; private set; }
        public Statistic Articles { get; private set; }
        public Statistic Videos { get; private set; }

        public StatisticUsersStatus StatisticUsersStatus { get; private set; }
        
        public async Task<IActionResult> OnGet()
        {
            if (CurrentUser is null)
            {
                return Redirect(nameof(Authorization));
            }
            
            if (CurrentUser.Role != Role.Administrator)
            {
                return Redirect($"~/{nameof(Account)}/{CurrentUser.Id}");
            }

            Registrations = await AdminStatistics
                .Create<User>(_adminRepository, a => DateTime.Now - a.Registration < TimeSpan.OneDay);
            
            Articles = await AdminStatistics
                .Create<Article>(_adminRepository, a => DateTime.Now - a.Publication < TimeSpan.OneDay);
            
            Videos = await AdminStatistics
                .Create<Models.Video>(_adminRepository, a => DateTime.Now - a.Publication < TimeSpan.OneDay);

            StatisticUsersStatus = await StatisticUsersStatus.CreateAsync(_adminRepository);
            
            return Page();
        }

        public async Task<IActionResult> OnGetUsersShowMore(int skip, int take)
        {
            if (skip < 0 || take < 0) return BadRequest();
            var users = await _adminRepository.GetCollectionAsync<User>(skip, take);
            return Partial("Partials/AdminGettingUsers", users);
        }
    }
}

2021/FALL/FISD/SEM/Science/Science/Pages/AdminDirectory/Partials/AdminGettingUsers.cshtml
@using Science.Models
@model IEnumerable<Science.Models.User>
@foreach (var user in Model)
{
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-center">
                    <a asp-page="/AccountDirectory/Account" asp-route-userid="@user.Id">
                        @user.Login
                    </a>
                </h5>
                <p class="card-text mt-1 mb-0">Фамилия: @user.SecondName</p>
                <p class="card-text mt-1 mb-0">Имя: @user.FirstName</p>
                <p class="card-text mt-1 mb-0">Регистрация: @user.Registration.ToString("dd.MM.yyyy")</p>
                <p class="card-text mt-1 mb-0">Роль: @user.Role.ToRussianLanguage()</p>
                <p class="card-text mt-1 mb-0">Статус: @user.Status.ToRussianLanguage()</p>
            </div>
        </div>
    </div>
}

2021/FALL/FISD/SEM/Science/Science/Pages/AdminDirectory/Partials/AdminStatistic.cshtml
@model Science.Pages.AdminDirectory.Admin

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
    <div class="col">
        <div class="card">
            <div class="d-flex justify-content-center">
                <div class="">
                    <img src="images/admin/registered_users.jpg"
                         class="card-img-top" alt="registered_users.jpg">
                </div>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center">Регистраций</h5>
                <p class="card-text mb-0">Всего: @Model.Registrations.Key</p>
                <p class="card-text mt-1">Сегодня: @Model.Registrations.Value</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <img src="images/admin/article.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Опубликовано статей</h5>
                <p class="card-text mb-0">Всего: @Model.Articles.Key</p>
                <p class="card-text mt-1">Сегодня: @Model.Articles.Value</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <img src="images/admin/video.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Опубликовано видео</h5>
                <p class="card-text mb-0">Всего: @Model.Videos.Key</p>
                <p class="card-text mt-1">Сегодня: @Model.Videos.Value</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <img src="images/admin/users_status.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Статусы пользователей</h5>
                <p class="card-text mb-0">Активных: @Model.StatisticUsersStatus.Active</p>
                <p class="card-text mb-0">Заблокированных: @Model.StatisticUsersStatus.Blocked</p>
                <p class="card-text mb-0">Удаленных: @Model.StatisticUsersStatus.Removed</p>
            </div>
        </div>
    </div>
</div>

2021/FALL/FISD/SEM/Science/Science/Pages/AdminDirectory/Partials/AdminUsers.cshtml
@model Science.Pages.AdminDirectory.Admin

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4" id="users-content"></div>
<div class="mt-3 text-center">
    <form method="get" id="form-admin-users-show-more" asp-page-handler="UsersShowMore">
        <input type="submit" class="show-more" value="Показать больше">
    </form>
</div>