2021/FALL/FISD/SEM/Science/Science/Pages/ArticleDirectory/Article.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Science.Infrastructure;
using Science.Infrastructure.Image;
using Science.Models;
using Science.Services;
using Science.Services.Database.ArticleDb;
using Science.Services.Database.ArticleReviewDb;
using Science.ViewModels;

namespace Science.Pages.ArticleDirectory
{
    public class Article : CommonPage
    {
        private readonly IArticleRepository _articleRepository;
        private readonly IArticleReviewRepository _articleReviewRepository;
        private readonly IImageHelper _imageHelper;

        public Article(IArticleRepository articleRepository, IArticleReviewRepository articleReviewRepository, IImageHelper imageHelper)
        {
            _articleRepository = articleRepository;
            _articleReviewRepository = articleReviewRepository;
            _imageHelper = imageHelper;
        }

        [BindProperty]
        public ArticleViewModel ArticleVm { get; set; }

        public Models.Article Art { get; set; }

        [BindProperty(SupportsGet = true)] 
        public int PageId { get; set; }

        private async Task SetAsync()
        {
            Art = await _articleRepository.FindByIdAsync(PageId);
        }
        
        private void AssignAccessToEdit()
        {
            IsAccessToEdit = Art.Publisher == CurrentUser;
        }

        public bool IsAccessToEdit { get; set; }
        
        private async Task UpdateAsync()
        {
            Art.Title = ArticleVm.Title;
            Art.Description = ArticleVm.Description;
            Art.Text = ArticleVm.Text;
            if (ArticleVm.Image is not null)
                Art.ImageName = ArticleVm.Image.FileName;
            
            await _articleRepository.UpdateAndSaveAsync(Art);
        }

        public async Task OnPostEdit()
        {
            await SetAsync();
            AssignAccessToEdit();
            
            if (ModelState.IsValid)
            {
                if (ArticleVm.Image is null)
                {
                    await UpdateAsync();
                    return;
                }

                if (!ArticleVm.Image.TryParseToImage(out var image))
                {
                    ModelState.AddModelError("ArticleVm.Image", ImageStatus.NotImage.GetErrorMessages());
                    return;
                }

                var status = _imageHelper.IsValid(image, 10);
                if (status != ImageStatus.Valid)
                {
                    ModelState.AddModelError("ArticleVm.Image", status.GetErrorMessages());
                    return;
                }

                var t1 = UpdateAsync();
                var t2 = _imageHelper.InsertPictureAsync(image, "images", "article", Art.Id.ToString(),
                    ArticleVm.Image.FileName);

                await Task.WhenAll(t1, t2);
            }
        } 
        
        public async Task<IActionResult> OnPostBlock()
        {
            await SetAsync();
            if (Art is null || Art.Status != Status.Active) return BadRequest();
            await _articleRepository.BlockAndSaveAsync(Art);
            return Redirect("~/Articles");
        }
        
        public async Task<IActionResult> OnPostDelete()
        {
            await SetAsync();
            if (Art is null || Art.Status != Status.Active) return BadRequest();
            await _articleRepository.DeleteAndSaveAsync(Art);
            return Redirect("~/Articles");
        }
        
        public async Task<IActionResult> OnPostRestore()
        {
            await SetAsync();
            if (Art is null || Art.Status != Status.Removed) return BadRequest();
            await _articleRepository.MakeActiveAndSaveAsync(Art);
            return Redirect($"~/Article/{Art.Id}");
        }
        
        public async Task<IActionResult> OnPostCommentAsync(string comment)
        {
            await SetAsync();

            if (comment is null
                || comment.Length > 300
                || comment.Contains("<script>"))
            {
                return new BadRequestResult();
            }

            var resultComment = new CommentViewModel(comment);
            var commentModel = await _articleReviewRepository.AddAndSaveAsync(Art, CurrentUser, resultComment);
            
            return ViewComponent("Comment", new { comment = commentModel });
        }

        public async Task<IActionResult> OnGet()
        {
            await SetAsync();
            if (Art is null || Art.Status != Status.Active) return NotFound();
            AssignAccessToEdit();
            if (IsAccessToEdit)
            {
                ArticleVm = new ArticleViewModel(Art);
            }
            return Page();
        }

        public async Task<IActionResult> OnGetShowMoreAsync(int skip, int take)
        {
            await SetAsync();
            return ViewComponent("Comment", new {skip, take, article = Art});
        }

        public async Task<IActionResult> OnPostBlockComment(int blockedCommentId)
        {
            await SetAsync();
            AssignAccessToEdit();
            var comment = await _articleReviewRepository.FindById(blockedCommentId);
            if (comment is null || !IsAdmin && CurrentUser.Role != Role.Moderator) return BadRequest();
            await _articleReviewRepository.BlockAndSaveAsync(comment);
            return Page();
        }
    }
}

2021/FALL/FISD/SEM/Science/Science/Pages/ArticleDirectory/Articles.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Science.Infrastructure;
using Science.Infrastructure.Image;
using Science.Models;
using Science.Services;
using Science.Services.Database.ArticleDb;
using Science.ViewModels;
using SixLabors.ImageSharp;

namespace Science.Pages.ArticleDirectory
{
    public class Articles : CommonPage
    {
        [BindProperty(SupportsGet = true)] 
        public int CurrentPage { get; set; } = 1;

        public Pagination Pagination { get; set; }

        [BindProperty]
        public ArticleViewModel ArticleVm { get; set; }

        private readonly IArticleRepository _articleRepository;
        private readonly IImageHelper _imageHelper;
        public IEnumerable<Models.Article> ArticlesModel { get; set; }

        public Articles(IArticleRepository articleRepository, IImageHelper imageHelper)
        {
            _articleRepository = articleRepository;
            _imageHelper = imageHelper;
        }

        private async Task AssignAsync()
        {
            var countRecords = await _articleRepository.GetCountRecords();
            Pagination = new Pagination(CurrentPage, countRecords, nameof(Articles), 5);
            ArticlesModel = await _articleRepository.FindResultPagination(Pagination.CurrentPage, Pagination.PageSize);
        }
        
        public async Task<IActionResult> OnGet()
        {
            if (CurrentPage <= 0) return NotFound();
            await AssignAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostAddingAsync()
        {
            await AssignAsync();
            if (!ModelState.IsValid) return Page();

            Image image = null;
            
            if (ArticleVm.Image is not null)
            {
                var isImage = ArticleVm.Image.TryParseToImage(out image);
            
                if (!isImage)
                {
                    ModelState.AddModelError("ArticleVm.Image", ImageStatus.NotImage.GetErrorMessages());
                    return Page();   
                }
            
                var imageStatus = _imageHelper.IsValid(image, 10);
                if (imageStatus != ImageStatus.Valid)
                {
                    ModelState.AddModelError("ArticleVm.Image", imageStatus.GetErrorMessages());
                    return Page();   
                }
            }
            
            if (CurrentUser is null
                || CurrentUser.Role == Role.CommonUser
                || CurrentUser.Status != Status.Active)
            {
                ModelState.AddModelError("", "У вас нет прав");
                return Page();   
            }

            var article = await _articleRepository.AddAndSaveAsync(ArticleVm, CurrentUser);
            var pathToDirectory = Path.Combine("images", "article", article.Id.ToString());
            _imageHelper.CreateDirectory(pathToDirectory);

            if (ArticleVm.Image is not null)
            {
                await _imageHelper.InsertPictureAsync(image, pathToDirectory, ArticleVm.Image.FileName);
                return Redirect($"/Article/{article.Id}");
            }
            
            return Redirect($"/Article/{article.Id}");
        }
    }
}

2021/FALL/FISD/SEM/Science/Science/Pages/ArticleDirectory/Partial/ArticleAdding.cshtml
@model Science.Pages.ArticleDirectory.Articles

<div class="modal fade" id="modal-window-add" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Добавление</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="validation" asp-validation-summary="ModelOnly"></div>
                <form method="post" asp-page-handler="Adding" id="form-add"  enctype="multipart/form-data">
                    <label asp-for="ArticleVm.Image"></label>
                    <div class="mb-3">
                        <input accept="image/*" class="form-control" asp-for="ArticleVm.Image"/>
                        <span class="text-danger" asp-validation-for="ArticleVm.Image"></span>
                    </div>
                    
                    <label asp-for="ArticleVm.Title"></label>
                    <div class="mb-3">
                        <input class="form-control" asp-for="ArticleVm.Title"/>
                        <span class="text-danger" asp-validation-for="ArticleVm.Title"></span>
                    </div>
                    
                    <label asp-for="ArticleVm.Description"></label>
                    <div class="mb-3">
                        <textarea class="form-control" asp-for="ArticleVm.Description"></textarea>
                        <span class="text-danger" asp-validation-for="ArticleVm.Description"></span>
                    </div>

                    <label asp-for="ArticleVm.Text"></label>
                    <div class="mb-3">
                        <textarea class="form-control" asp-for="ArticleVm.Text"></textarea>
                        <span class="text-danger" asp-validation-for="ArticleVm.Text"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <input type="submit" class="btn btn-primary" value="Добавить" form="form-add">
            </div>
        </div>
    </div>
</div>

2021/FALL/FISD/SEM/Science/Science/Pages/ArticleDirectory/Partial/ArticleEditing.cshtml
@model Science.Pages.ArticleDirectory.Article

<div class="modal fade" id="modal-window-edit" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Добавление</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="validation" asp-validation-summary="ModelOnly"></div>
                <form method="post" asp-page-handler="Edit" id="form-add" enctype="multipart/form-data">
                    <div class="w-100 h-100 position-relative">
                        <div class="text-center">
                            <label asp-for="ArticleVm.Image" class="">
                                <img class="profile-img rounded-circle"
                                     id="img"
                                     src="/images/article/@Model.Art.Id/@Model.Art.ImageName"
                                     alt="Не удалось загрузить изображение">
                            </label>
                        </div>
                        <span class="text-danger" asp-validation-for="ArticleVm.Image"></span>
                        <div class="mb-3 position-absolute top-0 start-0 w-100 h-100" style="opacity: 0">
                            <input type="file" accept="image/*" asp-for="ArticleVm.Image"
                                   class="w-100 h-100">
                        </div>
                    </div>

                    <label asp-for="ArticleVm.Title"></label>
                    <div class="mb-3">
                        <input class="form-control" asp-for="ArticleVm.Title"/>
                        <span class="text-danger" asp-validation-for="ArticleVm.Title"></span>
                    </div>

                    <label asp-for="ArticleVm.Description"></label>
                    <div class="mb-3">
                        <textarea class="form-control" asp-for="ArticleVm.Description"></textarea>
                        <span class="text-danger" asp-validation-for="ArticleVm.Description"></span>
                    </div>

                    <label asp-for="ArticleVm.Text"></label>
                    <div class="mb-3">
                        <textarea class="form-control" asp-for="ArticleVm.Text"></textarea>
                        <span class="text-danger" asp-validation-for="ArticleVm.Text"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <input type="submit" class="btn btn-primary" value="Изменить" form="form-add">
            </div>
        </div>
    </div>
</div>