2022/FISD/HW4_db_mvc_12.03.2022/Project/Project/Models/ErrorViewModel.cs
namespace Project.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

2022/FISD/HW4_db_mvc_12.03.2022/Project/Project/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Filters;
using Project.Infrastructure.Constants;
using Project.Services.Db.SessionRepository;
using Project.Services.Db.UserRepository;
using Project.Services.Hashing;
using Project.Services.RandomBytes;
using Project.SharedKernel.Extensions;

namespace Project.Controllers;

public class AccountController : Controller
{
    private readonly IUserRepository _userRepository;
    private readonly ISessionRepository _sessionRepository;
    private readonly IRandomer _randomer;
    private readonly IHashing _hashing;

    public AccountController(IUserRepository userRepository, 
        ISessionRepository sessionRepository, 
        IRandomer randomer,
        IHashing hashing)
    {
        _userRepository = userRepository;
        _sessionRepository = sessionRepository;
        _randomer = randomer;
        _hashing = hashing;
    }

    [HttpGet]
    [ActionName("SignIn")]
    [AuthorizationFilter(PageConstants.Main)]
    public IActionResult OnGetSignIn()
    {
        return View();
    }
    
    [HttpPost]
    [ActionName("SignIn")]
    [AuthorizationFilter(PageConstants.Main)]
    public async Task<IActionResult> OnPostSignIn(string login, string password, bool isRemember)
    {
        var user = await _userRepository.FindByLoginAsync(login);
        
        if (user is null || _hashing.Hash(password, user.Salt) != user.HashedPassword)
        {
            return BadRequest();
        }

        if (isRemember)
        {
            var token = _randomer.Generate(40).Join();
            Response.Cookies.Append("token", token);
            await _sessionRepository.AddAndSaveAsync(new Session(user, token));
        }
        else
        {
            HttpContext.Session.SetString("login", user.Login); 
        }
        
        return Redirect($"{PageConstants.UserAccount}/{user.Login}");
    }

    [HttpGet]
    [ActionName("SignUp")]
    [AuthorizationFilter(PageConstants.Main)]
    public IActionResult OnGetSignUp()
    {
        return View();
    }

    [HttpPost]
    [ActionName("SignUp")]
    [AuthorizationFilter(PageConstants.Main)]
    public async Task<IActionResult> OnPostSignUp(string login, string password)
    {
        var isUserExists = await _userRepository.FindByLoginAsync(login) is not null;
        
        if (isUserExists)
        {
            return new ConflictResult();
        }

        var salt = _randomer.Generate(20);
        var hashedPassword = _hashing.Hash(password, salt);
        
        var user = new User
        {
            HashedPassword = hashedPassword,
            Login = login,
            Salt = salt
        };
        
        await _userRepository.AddAndSaveAsync(user);
        return Redirect($"{PageConstants.UserAccount}/{user.Login}");
    }

    [Route("/Account/Index/{login?}")]
    [AuthorizationFilter(PageConstants.Authorization, true)]
    public async Task<IActionResult> Index(string login)
    {
        var user = await _userRepository.FindByLoginAsync(login);
        
        if (user is null)
        {
            return NotFound();
        }
        
        return View(user);
    }
}

2022/FISD/HW4_db_mvc_12.03.2022/Project/Project/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MimeTypes;
using Project.Extensions;
using Project.Filters;
using Project.Services.FileHelper;

namespace Project.Controllers;

public class FileController : Controller
{
    private readonly IFileHelper _fileHelper;
    private readonly AppDbContext _dbContext;
    private readonly string _pathToDirectory;

    public FileController(IHostEnvironment environment, IFileHelper fileHelper, AppDbContext dbContext)
    {
        _fileHelper = fileHelper;
        _dbContext = dbContext;
        _pathToDirectory = string.Join("/", environment.ContentRootPath, "files") + "/";
    }

    [HttpGet]
    public IActionResult Index()
    {
        var files = Directory.EnumerateFiles(_pathToDirectory).Select(Path.GetFileName);
        return View(files);
    }

    [HttpGet]
    public async Task<IActionResult> ShowTxtFile(string fileName)
    {
        var ext = Path.GetExtension(fileName);

        if (ext != ".txt")
        {
            return BadRequest($"Вы не можете открыть не файл с расширением {ext}");
        }

        var content = await _fileHelper.FindContentFileAsync("files/" + fileName);

        if (content is null)
        {
            return new NotFoundObjectResult($"{fileName} не найден");
        }

        return new JsonResult(content);
    }

    [HttpPost]
    [AuthorizationFilter("/File/", true)]
    public async Task<IActionResult> SaveFileAsync(string fileName, string content)
    {
        var isOk = await _fileHelper.TryOverwriteAsync("files/" + fileName, content);

        if (!isOk)
        {
            return BadRequest("Что-то пошло не так");
        }
        
        var file = _dbContext.FileInfos.Include(f => f.FileHistories)
            .FirstOrDefault(f => f.Title == fileName);
        
        file!.FileHistories.Add(new FileHistory
        {
            FileAction = FileAction.Changed
        });
        
        await _dbContext.SaveChangesAsync();
        

        return Redirect("/File");
    }

    [HttpGet]
    public IActionResult DownloadFile(string fileName)
    {
        var path = Path.Combine(_pathToDirectory, fileName);

        if (!System.IO.File.Exists(path)) return BadRequest();

        var extension = Path.GetExtension(fileName);
        var mimeType = MimeTypeMap.GetMimeType(extension);
        return new PhysicalFileResult(path, mimeType);
    }

    [HttpPost]
    [AuthorizationFilter("/File/", true)]
    public async Task<IActionResult> DeleteFileAsync(string fileName)
    {
        var path = _pathToDirectory + fileName;

        if (!System.IO.File.Exists(path)) return RedirectToAction("Index");
        
        var fileInfo = _dbContext.FileInfos.FirstOrDefault(fi => fi.Title == fileName);
        var user = HttpContext.FindUser();
        var fileHistory = new FileHistory
        {
            FileAction = FileAction.Removed,
            FileInfo = fileInfo!,
        };
            
        user!.FileHistories.Add(fileHistory);

        await _dbContext.AddAsync(fileHistory);
        await _dbContext.SaveChangesAsync();
        System.IO.File.Delete(path);
        return RedirectToAction("Index");
    }

    [HttpPost]
    [AuthorizationFilter("/File/", true)]
    public async Task<IActionResult> AddFileAsync(IFormFile file)
    {
        var pathToFile = _pathToDirectory + file.FileName;
        await using var stream = System.IO.File.Create(pathToFile);
        await file.CopyToAsync(stream);
        
        var fileInfo = new FileInformation
        {
            Title = file.FileName,
            Extension = Path.GetExtension(file.FileName),
        };

        await _dbContext.AddAsync(fileInfo);
        
        var fileHistory = new FileHistory
        {
            FileAction = FileAction.Created,
            FileInfo = fileInfo
        };

        await _dbContext.AddAsync(fileHistory);

        var user = HttpContext.FindUser();
        user!.FileHistories.Add(fileHistory);

        await _dbContext.SaveChangesAsync();
        return RedirectToAction("Index");
    }
}

2022/FISD/HW4_db_mvc_12.03.2022/Project/Project/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Project.Models;
using Project.SharedKernel;

namespace Project.Controllers;

public class HomeController : Controller
{ 
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }

    public IActionResult NotAuthorized()
    {
        return View();
    }
}

2022/FISD/HW4_db_mvc_12.03.2022/Project/Project/Views/Shared/_Layout.cshtml
@using Project.Extensions

@{
    var user = Context.FindUser();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Project.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="Index">File Manager</a>
                    </li>
                    @if (user is null)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignIn">Sign in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">Sign up</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index" asp-route-login="@user.Login">Личный кабинет</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>