2021/FALL/FISD/SEM/Science/Science/Models/Scientist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Science.Models
{
    public class Scientist
    {
        public int Id { get; set; }

        [Required]
        public User Publisher { get; set; }

        [Required]
        [Column(TypeName = "varchar(30)")]
        public string FirstName { get; set; }

        [Required]
        [Column(TypeName = "varchar(50)")]
        public string SecondName { get; set; }
        
        [Column(TypeName = "varchar(40)")]
        public string Patronymic { get; set; }

        [Required]
        [Column(TypeName = "date")]
        public DateTime Birth { get; set; }

        [Column(TypeName = "date")]
        public DateTime? Death { get; set; }

        [Column(TypeName = "varchar(100)")]
        public string PhotoName { get; set; }

        [Required]
        public Status Status { get; set; }
        
        [Required]
        [Column(TypeName = "varchar(1000)")]
        public string Biography { get; set; }
        
        public ICollection<ScientificWork> ScientificWorks { get; set; }

        [Required]
        public ICollection<AreaScience> AreaSciences { get; set; }
    }
}

2021/FALL/FISD/SEM/Science/Science/ViewModels/ScientistViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace Science.ViewModels
{
    public class ScientistViewModel
    {
        [Required]
        [MaxLength(30)]
        [DisplayName("Имя")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(50)]
        [DisplayName("Фамилия")]
        public string SecondName { get; set; }
        
        [MaxLength(40)]
        [DisplayName("Отчество")]
        public string Patronymic { get; set; }

        [Required]
        [DisplayName("Дата рождения")]
        public DateTime Birth { get; set; }

        [DisplayName("Дата смерти")]
        public DateTime? Death { get; set; }

        [Required]
        [DisplayName("Фото")]
        public IFormFile Photo { get; set; }

        [Required]
        [MaxLength(1000)]
        [DisplayName("Биография")]
        public string Biography { get; set; }

        [Required] 
        [DisplayName("Научные области")]
        public int[] AreaSciencesId { get; set; }
    }
}

2021/FALL/FISD/SEM/Science/Science/Pages/ScientistDirectory/Scientist.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Science.Infrastructure;
using Science.Infrastructure.Image;
using Science.Models;
using Science.Services;
using Science.Services.Database.AreaScienceDb;
using Science.Services.Database.ScientificWorkDb;
using Science.Services.Database.ScientistDb;
using Science.ViewModels;
using JsonResult = Microsoft.AspNetCore.Mvc.JsonResult;

namespace Science.Pages.ScientistDirectory
{
    public class Scientist : CommonPage
    {
        private readonly IScientistRepository _scientistRepository;
        private readonly IScientificWorkRepository _scientificWorkRepository;
        private readonly IAreaScienceRepository _areaScienceRepository;
        private readonly IImageHelper _imageHelper;

        public List<SelectListItem> Options { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public int PageId { get; set; }

        [BindProperty]
        public ScientificWorkViewModel ScientificWorkVm { get; set; }

        [BindProperty] 
        [DisplayName("Научные труды")]
        public int[] ScientificWorksId { get; set; }

        public bool IsAccessToEdit { get; set; }
        
        public Scientist(IScientistRepository scientistRepository, 
            IScientificWorkRepository scientificWorkRepository, IAreaScienceRepository areaScienceRepository, IImageHelper imageHelper)
        {
            _scientistRepository = scientistRepository;
            _scientificWorkRepository = scientificWorkRepository;
            _areaScienceRepository = areaScienceRepository;
            _imageHelper = imageHelper;
        }

        public Models.Scientist ScientistModel { get; set; }

        private async Task UpdateScientistAsync()
        {
            await _scientistRepository.UpdateAndSaveAsync(ScientistVm, ScientistModel);
        }

        [BindProperty]
        public int DeleteFromOne { get; set; }
        
        [BindProperty]
        public int DeleteFromAll { get; set; }
        
        [BindProperty]
        public int Block { get; set; }

        public async Task<IActionResult> OnPostDeleteWorkFromOne()
        {
            await AssignAsync();
            if (DeleteFromOne <= 0) return BadRequest();
            var sw = ScientistModel.ScientificWorks.FirstOrDefault(a => a.Id == DeleteFromOne);
            if (sw == null) return BadRequest();
            await _scientificWorkRepository.DeleteFromOneAndSaveAsync(sw, ScientistModel);
            return Redirect($"~/Scientist/{ScientistModel.Id}");
        }
        
        public async Task<IActionResult> OnPostDeleteWorkFromAll()
        {
            await AssignAsync();
            if (DeleteFromAll <= 0) return BadRequest();
            var sw = ScientistModel.ScientificWorks.FirstOrDefault(a => a.Id == DeleteFromAll);
            if (sw == null) return BadRequest();
            if (sw.Status != Status.Active) return BadRequest();
            await _scientificWorkRepository.DeleteFromAllAndSaveAsync(sw);
            return Redirect($"~/Scientist/{ScientistModel.Id}");
        }

        public async Task<IActionResult> OnPostWorkBlock()
        {
            await AssignAsync();
            if (Block <= 0) return BadRequest();
            var sw = ScientistModel.ScientificWorks.FirstOrDefault(a => a.Id == Block);
            if (sw == null) return BadRequest();
            if (sw.Status != Status.Active) return BadRequest();
            await _scientificWorkRepository.BlockAndSaveAsync(sw);
            return Redirect($"~/Scientist/{ScientistModel.Id}");
        }

        public async Task<IActionResult> OnPostRestore()
        {
            await AssignAsync();
            if (ScientistModel.Status != Status.Removed) return BadRequest();
            await _scientistRepository.MakeActiveAndSaveAsync(ScientistModel);
            return Redirect($"/Scientist/{ScientistModel.Id}");
        }
        
        public async Task<IActionResult> OnPostBlock()
        {
            await AssignAsync();
            if (ScientistModel is null || ScientistModel.Status != Status.Active) return RedirectToPage("~/Scientists");
            ScientistModel.Status = Status.Blocked;
            await _scientistRepository.UpdateAndSaveAsync(ScientistModel);
            return Redirect("~/Scientists");
        }
        
        [BindProperty]
        public ScientistViewModel ScientistVm { get; set; }

        public async Task<IActionResult> OnPostDelete()
        {
            await AssignAsync();
            AssignAccessToEdit();
            await _scientistRepository.DeleteAndSaveAsync(ScientistModel);
            return Redirect("~/Scientists");
        }

        public async Task OnPostEdit()
        {
            await AssignAsync();
            AssignAccessToEdit();
            
            if (ModelState.ErrorCount is 2 or 3)
            {
                foreach (var value in ModelState.Values)
                {
                    value.Errors.Clear();
                }

                if (ScientistVm.Photo is null)
                {
                    await UpdateScientistAsync();
                    return;
                }

                if (!ScientistVm.Photo.TryParseToImage(out var image))
                {
                    ModelState.AddModelError("ScientistVm.Photo", ImageStatus.NotImage.GetErrorMessages());
                    return;
                }

                var status = _imageHelper.IsValid(image, 10);
                if (status != ImageStatus.Valid)
                {
                    ModelState.AddModelError("ScientistVm.Photo", status.GetErrorMessages());
                    return;
                }

                var t1 = _imageHelper.InsertPictureAsync(image, "images", "scientist", ScientistModel.Id.ToString(),
                    ScientistVm.Photo.FileName);
                var t2 = UpdateScientistAsync();
                
                await Task.WhenAll(t1, t2);
            }
        }

        private async Task AssignAsync()
        {
            ScientistModel = await _scientistRepository.FindById(PageId);
        }

        private void AssignAccessToEdit()
        {
            IsAccessToEdit = ScientistModel.Publisher == CurrentUser;
        }
        
        public async Task<IActionResult> OnGet()
        {
            await AssignAsync();
            if (ScientistModel is null || ScientistModel.Status != Status.Active) return NotFound();
            AssignAccessToEdit();
            Options = _areaScienceRepository.GetAreaSciencesSelectListItem().ToList();
            foreach (var option in Options
                .Where(option => ScientistModel.AreaSciences
                    .Select(a => a.Id)
                    .Contains(int.Parse(option.Value))))
            {
                option.Selected = true;
            }

            ScientistVm = new ScientistViewModel
            {
                FirstName = ScientistModel.FirstName,
                SecondName = ScientistModel.SecondName,
                Patronymic = ScientistModel.Patronymic,
                Biography = ScientistModel.Biography,
                Birth = ScientistModel.Birth,
                Death = ScientistModel.Death
            };
            
            return Page();
        }

        public async Task<IActionResult> OnPostAddScientificWork()
        {
            ScientistModel = await _scientistRepository.FindById(PageId);
            await _scientificWorkRepository.AddAndSaveAsync(ScientificWorkVm, CurrentUser, ScientistModel);
            return Redirect($"~/Scientist/{ScientistModel.Id}");
        }

        public async Task<IActionResult> OnGetScientificWorks(string term)
        {
            ScientistModel = await _scientistRepository.FindById(PageId);
            term ??= "";
            
            var scientificWorks = _scientificWorkRepository
                .GetScientificWorks(term, 20, ScientistModel)
                .Select(sw => new JsonOptionsSelect2(sw.Id, sw.Title)).ToList();
            
            var result = new JsonResult(scientificWorks)
            {
                ContentType = "json",
                StatusCode = 200
            };
            
            return new JsonResult(result);
        }

        public async Task OnPostUpdatingScientificWork()
        {
            ScientistModel = await _scientistRepository.FindById(PageId);
            await _scientificWorkRepository.UpdateAndSaveAsync(ScientificWorksId, ScientistModel);
        }
    }
}

2021/FALL/FISD/SEM/Science/Science/Pages/ScientistDirectory/Scientists.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Science.Infrastructure;
using Science.Infrastructure.Image;
using Science.Models;
using Science.Services;
using Science.Services.Database.AreaScienceDb;
using Science.Services.Database.ScientificWorkDb;
using Science.Services.Database.ScientistDb;
using Science.ViewModels;

namespace Science.Pages.ScientistDirectory
{
    public class Scientists : CommonPage
    {
        private readonly IScientistRepository _scientistRepository;
        private readonly IAreaScienceRepository _areaScienceRepository;
        private readonly IScientificWorkRepository _scientificWorkRepository;
        private readonly IImageHelper _imageHelper;

        public List<SelectListItem> Options { get; set; }

        public Scientists(
            IScientistRepository scientistRepository,
            IAreaScienceRepository areaScienceRepository,
            IImageHelper imageHelper, 
            IScientificWorkRepository scientificWorkRepository)
        {
            _areaScienceRepository = areaScienceRepository;
            _imageHelper = imageHelper;
            _scientificWorkRepository = scientificWorkRepository;
            _scientistRepository = scientistRepository;
        }

        public IEnumerable<Models.Scientist> ScientistsModel { get; set; }

        [BindProperty(SupportsGet = true)] 
        public int CurrentPage { get; set; } = 1;

        [BindProperty] 
        public ScientistViewModel ScientistVm { get; set; }
        
        public Pagination Pagination { get; set; }

        private async Task AssignAsync()
        {
            var count = await _scientistRepository.GetCountRecords();
            Pagination = new Pagination(CurrentPage, count, nameof(Scientists), 4);
            ScientistsModel = await _scientistRepository.FindResultPagination(Pagination.CurrentPage, Pagination.PageSize);
            Options = _areaScienceRepository.GetAreaSciencesSelectListItem().ToList();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            if (CurrentPage <= 0) return NotFound();
            await AssignAsync();
            return Page();
        }
        
        [BindProperty(SupportsGet = true)]
        public int Restore { get; set; }
        
        public async Task<IActionResult> OnPostWorkRestore()
        {
            await AssignAsync();
            if (Restore <= 0) return BadRequest();
            var sw = await _scientificWorkRepository.FindById(Restore);
            if (sw == null) return BadRequest();
            if (sw.Status != Status.Removed) return BadRequest();
            await _scientificWorkRepository.RestoreAndSaveAsync(sw);
            return Redirect("~/Scientists");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await AssignAsync();

            if (!ModelState.IsValid) return Page();
            
            var isImage = ScientistVm.Photo.TryParseToImage(out var image);
            if (!isImage)
            {
                ModelState.AddModelError("ScientistVm.Photo", "Ожидалась картинка");
                return Page();
            }

            var status = _imageHelper.IsValid(image, 10);
            if (status != ImageStatus.Valid)
            {
                ModelState.AddModelError("ScientistVm.Photo", status.GetErrorMessages());
                return Page();
            }
                
            await _scientistRepository.AddAndSave(ScientistVm, CurrentUser);
            var scientist = await _scientistRepository.FindByFullNameAndBirthAsync(ScientistVm.FirstName,
                ScientistVm.SecondName, ScientistVm.Patronymic, ScientistVm.Birth);
                
            _imageHelper.CreateDirectory("images", "scientist", scientist.Id.ToString());

            await _imageHelper.InsertPictureAsync(image, "images", "scientist", scientist.Id.ToString(),
                ScientistVm.Photo.FileName);

            return Redirect($"~/Scientist/{scientist.Id}");
        }
    }
}

2021/FALL/FISD/SEM/Science/Science/Pages/ScientistDirectory/Scientist.cshtml
@page "{PageId}"
@using Science.Models
@model Science.Pages.ScientistDirectory.Scientist


<div class="mt-3">
    <div class="d-flex justify-content-md-start justify-content-center">
        <div>
            <div class="col-md-auto position-relative" style="height: 200px; max-width: 200px">
                <image path="/images/scientist/@Model.ScientistModel?.Id/@Model.ScientistModel?.PhotoName"></image>

                @if (Model.IsAdmin)
                {
                <div class="position-absolute bottom-0 start-0 ms-1 mb-1">
                    <div class="">
                        <form method="post">
                            <button type="submit" class="btn btn-primary" asp-page-handler="block">
                                <i class="fas fa-bullhorn"></i>
                            </button>
                        </form>
                    </div>
                </div>
                }
                @if (Model.IsAccessToEdit)
                {
                    <div class="position-absolute bottom-0 end-0 me-1 mb-1">
                        <div class="d-flex flex-row">
                            <div class="">
                                <button type="button" class="btn btn-primary"
                                        data-bs-toggle="modal" data-bs-target="#modal-window-edit">
                                    <i class="fas fa-edit"></i>
                                </button>
                                <partial name="Partial/ScientistEditing"></partial>
                            </div>
                            <div class="ms-1">
                                <form method="post">
                                    <button type="submit" class="btn btn-primary" asp-page-handler="delete">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="text-center">
                <h5 class="mt-1 mb-1">
                    @Model.ScientistModel?.SecondName @Model.ScientistModel?.FirstName @Model.ScientistModel?.Patronymic
                </h5>
                <h6 class="mt-1 mb-1">
                    @Model.ScientistModel?.Birth.ToString("dd.MM.yyyy") - @(Model.ScientistModel?.Death?.ToString("dd.MM.yyyy") ?? "настоящее время")
                </h6>
                @{
                    if (Model.CurrentUser is not null && Model.IsAccessToEdit)
                    {
                        <button type="button" class="btn btn-primary"
                                data-bs-toggle="modal" data-bs-target="#modal-window-add">
                            Добавить новый труд
                        </button>
                        <partial name="Partial/ScientificWorkAdding"></partial>

                        <div class="mt-3">
                            <form method="post" asp-page-handler="UpdatingScientificWork" id="form-update">
                                <label asp-for="ScientificWorksId"></label>
                                <div class="mb-3 w-100">
                                    <select class="form-control" style="width: 100%" asp-for="ScientificWorksId"></select>
                                    <span class="text-danger" asp-validation-for="ScientificWorksId"></span>
                                </div>
                                <button class="btn btn-primary" type="submit">Добавить к существующему</button>
                            </form>
                        </div>
                    }
                }
            </div>
        </div>
        <div class="w-100">
            <div class="ms-5">
                <div class="mb-3">
                    <div class="text-center">
                        <h4>Биография</h4>
                    </div>
                    <div>@Model.ScientistModel?.Biography</div>
                </div>
                <div>
                    <partial name="Partial/ScientistAddInfo"></partial>
                </div>
            </div>
        </div>

    </div>
</div>

2021/FALL/FISD/SEM/Science/Science/Pages/ScientistDirectory/Scientists.cshtml
@page "{CurrentPage:int?}"
@model Science.Pages.ScientistDirectory.Scientists

<div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
    @foreach (var scientist in Model.ScientistsModel)
    {
        <div class="col holder">
            <div class="card">
                <img src="~/images/scientist/@scientist.Id/@scientist.PhotoName"
                     class="card-img-top h-100 w-100" style="object-fit: cover" alt="Не удалось загрузить изображение">
                <div class="card-body text-center">
                    <a asp-page="/ScientistDirectory/Scientist" asp-route-PageId="@scientist.Id">
                        <h5 class="card-title">@scientist.SecondName @scientist.FirstName @scientist.Patronymic</h5>
                    </a>
                    <p class="card-text">@scientist.Birth.ToString("dd.MM.yyyy") - @(scientist.Death?.ToString("dd.MM.yyyy") ?? "настоящее время")</p>
                </div>
            </div>

            <div class="block text-center">
                <h3>Научные области</h3>
                @foreach (var area in scientist.AreaSciences.Take(2))
                {
                    <a asp-page="/AreaDirectory/Area" asp-route-pageId="@area.Id">
                        <p>@area.Title</p>
                    </a>
                }
            </div>
        </div>
    }
</div>

<partial name="Shared/_ButtonAdd" model="@Model.CurrentUser"></partial>
<partial name="Shared/_Pagination" model="@Model"></partial>
<partial name="Partial/ScientistAdding"></partial>

@section Scripts
{
    <partial name="Shared/_ValidationScriptsPartial"></partial>
}